### ISSUE TITLE
panic: calling Direct3DCreate9: The specified program requires a newer version of Windows.

### ISSUE THREAD

**Issue by mzbab88** [gonutz/d3d9#1]
Hello. Really glad somebody decided to do this, this will probably be priceless for me.

I tried to compile samples\rotating_quad, it compiled, but it gives me this error:

```
panic: calling Direct3DCreate9: The specified program requires a newer version of Windows.

goroutine 1 [running, locked to thread]:
panic(0x514200, 0x12840110)
    C:/Go/src/runtime/panic.go:464 +0x326
main.check(0x25a0018, 0x12840110)
    C:/Users/User/GoPath/src/github.com/gonutz/d3d9/samples/rotating_quad/main.go:123 +0x44
main.main()
    C:/Users/User/GoPath/src/github.com/gonutz/d3d9/samples/rotating_quad/main.go:33 +0x1d8
```

I'm on windows 7, and I'm really puzzled by necessity of using anything newer for just calling a dll. Can you give me a hint on what to do? I'm ready to test anything for as long as it will take.

Probably this will work if this program would use syscall.NewLazyDLL or syscall.MustLoadDLL instead of syscall.Syscall, at least I was told so. Here are a few links:

http://noypi-linux.blogspot.ru/2012/04/golang-using-shared-libraries.html  Method 1 from here

https://github.com/golang/go/wiki/WindowsDLLs Example two from here

http://stackoverflow.com/questions/22949444/using-go-golang-to-get-windows-idle-time-getlastinputinfo-or-similar

https://golang.org/src/syscall/dll_windows.go

**Comment by gonutz** [comment]
Hi there! I have encountered similar problems on two test machines lately, both fail on initialization but with different error messages. I am still trying to figure out what is happening there.
First I thought it was because of an error in the d3d9.dll (in C:\Windows\System32) but that does not seem to be it.
As you can see in [the code](https://github.com/gonutz/d3d9/blob/master/IDirect3D9_windows.go#L164) I am using syscall.LoadLibrary to load the DLL. It should probably not make a difference whether you use a regular or a lazy DLL in go, it is just a matter of when the functions are loaded, they should still be there and work in any case. But I will try it anyway, just to be sure.
Can you make sure that you have the latest DirectX runtime installed? And maybe check your video driver. You can use dxdiag and run their tests.
As you can see I am currently still quite puzzled myself but be assured that I am working on the problem. One goal for me with this library was that programs should run without installing DLLs as Windows usually comes with d3d9.dll pre-installed on all versions. But as long as this problem exists this goal is not met so I really appreciate your help with this :)

**Comment by mzbab88** [comment]
Hmm, my drivers are relatively recent (5 months old). 

Dxdiag says everything is fine, though I don't see buttons to actually do any tests. No spinning cube is shown, it just says "all ok".

Directx webinstaller just says directx is installed and quits, maybe I should download and install it manually later from here https://support.microsoft.com/en-us/kb/179113

...By the way, do you have this same program (rotating_quad) written in C++ or C somewhere? Can you share source and binary?

**Comment by gonutz** [comment]
I do not have the C code for the sample but it should be straight forward to convert it if you want to try that. I am not sure that will help, though.

Maybe the problem is that the header files in the library are not compatible with your version of the DLL. Can you run the following program and post the output? For me the call works for version 31 and 32.

``` Go
package main

import (
    "fmt"
    "github.com/gonutz/d3d9"
)

func main() {
    if err := d3d9.Init(); err != nil {
        panic(err)
    }
    defer d3d9.Close()

    for version := uint(0); version <= d3d9.SDK_VERSION; version++ {
        d3d, err := d3d9.Create(version)
        if err == nil {
            fmt.Println("works for version", version)
            d3d.Release()
        } else {
            fmt.Println("does not work for version", version)
        }
    }
}

```

**Comment by mzbab88** [comment]
does not work for version 0
does not work for version 1
(skipped)
does not work for version 32

**Comment by gonutz** [comment]
Well, that is strange. Can you try increasing the maximum of the for-loop, e.g. `version <= 1000` and see if you have a higher version in your DLL? I thought that version 32 (which is `d3d9.SDK_VERSION`) was the latest version for Direct3D9 but maybe not?
Just to be sure, see if any version number succeeds for you.

**Comment by mzbab88** [comment]
Commented out //fmt.Println("does not work for version", version) and run from 0 to 1000, nothiing printed. Nope, nothing works.

**Comment by gonutz** [comment]
Can you download the [Dependency Walker](http://www.dependencywalker.com/) and open your d3d9.dll in it? The first answer on [stackoverflow](http://stackoverflow.com/questions/11717312/loadlibrary-project-dll-failed-the-specified-module-could-not-be-found) gives you a hint about possible problems. Can you check if your DLL is OK?
Also, what versions of Go and MinGW are you using?

**Comment by mzbab88** [comment]
I actually don't see d3d9.dll in dependencies. In both dependency walker and ida. SDL2 is here though.

go version
go version go1.6.1 windows/386

gcc --version
gcc (i686-win32-sjlj-rev1, Built by MinGW-W64 project) 5.2.0

Looks like I have 32bit go and 64bit mingw and everything else...

**Comment by gonutz** [comment]
Shouldn't you have MinGW 32 as well then? Calling into 64 Bit compiled C from 32 Bit Go seems a little risky I think...
Can you try installing MinGW 32 and then point your PATH to its bin directory instead and try to rebuild the library (`go install -a` I think) with that?
Do you have any other problems with CGo code using MinGW 64?

**Comment by mzbab88** [comment]
Sorry, I was wrong, both mingw and go are 32bit. Mingw I have installed right now is this one http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.2.0/threads-win32/sjlj/i686-5.2.0-release-win32-sjlj-rt_v4-rev1.7z

**Comment by mzbab88** [comment]
Interesting. Not sure what I changed, but now it doesn't print anything in terminal. It just opens and closes window very fast.

**Comment by mzbab88** [comment]
rotating_quad.exe prints panic only when run from emacs' eshell, but prints nothing in other terminals.

**Comment by mzbab88** [comment]
Managed to compile a simple C++ Direct3d9 program. Worked without downloading anything, I just got http://www.fourthwoods.com/dxtest.cpp and compiled with "g++ dxtest.cpp -o dxtest.exe -DUNICODE -ld3d9". Reference: http://blog.fourthwoods.com/2011/08/11/setting-up-mingw-for-directx/

So, directx works here. Should work. I still don't know where the message "The specified program requires a newer version of Windows" comes from, autosearch in golang's sources for this string yelled nothing.

**Comment by gonutz** [comment]
The program printing nothing in the regular terminal is because using the `build.bat` it is built with `-ldflags -H=windowsgui` which means it has no console when you run the program by double-clicking it. This disables all console output. If you build without that flag you will get the messages back but will also have a console window open in the back when you double-click the exe.

The C++ code uses `#pragma comment (lib, "d3d9.lib")` to include the lib file which this library does not. In this library the DLL is loaded at run-time and it uses basically a copy of MinGW's `d3d9.h`. This is to avoid a user not having it installed or having a different version. However, this may be the problem.
The definitions in the header file have to be compatible with the DLL code and the SDK_VERSION #define is (or was) increased by Microsoft whenever the code changes. This is why I thought using a different version number might work for you, because the DLL could have been built against an older header but it does not work for you so there is another problem...

Simply googleing for your error message shows me that it is the system error code [ERROR_OLD_WIN_VERSION](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681383%28v=vs.85%29.aspx) and gives me links to [stackoverflow](http://stackoverflow.com/questions/34076414/installing-visual-studio-community-2015-on-windows-7-sp1) indicating it might be solved by setting the compatibility option for the program and [someone on codeproject](http://www.codeproject.com/Questions/148054/WINXP-SP-The-specified-program-requires-a-newer-v) indicating that calling Direct3DCreate9 might not even set the global error message which syscall.Syscall checks for GetLastError according to the docs. This means simply commenting-out [lines 201-203](https://github.com/gonutz/d3d9/blob/master/IDirect3D9_windows.go#L201-203) (and replacing `callErr` with `_`) might do the trick.

**Comment by mzbab88** [comment]
Ahaha, yes, that fixed it! Thank you!

**Comment by gonutz** [comment]
Oh that's great to hear! What exactly was it that fixed it? The compatibility mode or commenting out the lines? I will either change the code then or add instructions to the readme.

**Comment by mzbab88** [comment]
Commenting out code. I never would've guessed that I just need to NOT check error code. I wonder what sets it to ERROR_OLD_WIN_VERSION though, but that doesn't matter that much.

By the way, maybe you know where I can download fxc.exe from Windows SDK? I want to compile samples/static_triangle. Never worked with shaders, but always wandered what those where.

**Comment by gonutz** [comment]
Oh alright then, I am going to change the code and not check the error there :)
Who knows what sets that error code but I guess you are right then, it does not matter.

The fxc.exe is located in your Windows Kit folder, see [this thread on stackexchange](http://gamedev.stackexchange.com/questions/93339/where-the-fxc-exe-is-located-in-windows-sdk). On my Windows 8.1 machine it is at `C:\Program Files (x86)\Windows Kits\8.1\bin`.
You can download the Windows SDK [from here](https://www.microsoft.com/en-us/download/details.aspx?id=8279).

Thank you very much for this bug report! Let me know if you encounter any other problems :)

**Comment by mzbab88** [comment]
Um, if that's not too problematic, can you upload fxc.exe and it's dependencies somewhere? For some reason, everything from microsoft refuses to install on my machine.

**Comment by gonutz** [comment]
I think I am not allowed to upload the exe, I am pretty sure this would be illegal, it is not open software. You should download the latest Windows SDK for your platform. I am not sure why it won't install on your machine, maybe the link I posted in my last comment is not correct for 32 bit Windows 7?
You could also try to find an old DirectX SDK online, they should have this utility as well...

**Comment by mzbab88** [comment]
Ok, I think I found alternative http://directx-sdk.soft32.com/free-download/ , let's look if it will install properly. Really dislike downloading a 600mb exe file just to get one tiny util, but oh well, microsoft is always about that.

**Comment by gonutz** [comment]
Hope that works for you, I remember endless download times for several SDKs as well but there are some useful samples in there too.

**Comment by mzbab88** [comment]
Ok, I installed DX SDK, I think. It stopped with error S1023 in process, but it looks like it installed most necessary stuff.

Do shaders in static_triangle.exe really work? I don't see any errors, but is this all it's supposed to show? I still don't know what shaders are supposed to do.

**Comment by gonutz** [comment]
The static_triangle sample should just display a pink triangle on a black background. If that is what you see it is fine.
Shaders replace the fixed-function pipeline (or just parts of it - you could set a pixel shader but keep the fixed-function vertex processing for example). In this sample the shaders are as simple as you can get, the vertex shader just passes the input coordinates to the pixel shader untransformed and the pixel shader just outputs magenta for all pixels. You can of course have different shaders for different effects but this sample is just to show you how to basically set things up from an API point of view, it is not about showing off fancy effects.
You can read about Direct3D9 and HSLS in the [MSDN online documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb219837%28v=vs.85%29.aspx). This should give you a good starting point and it also contains the full reference for the whole API for when you want to look up specific functions.
Note that this library does not wrap the D3DX extensions, just the core D3D9 API. This means there are no helper functions for loading bitmaps from file for example. There are also no effects, you can only use shaders directly from this wrapper, the effects stuff is an addtional API on top of that, included in D3DX.

**Comment by mzbab88** [comment]
Have any plans for doing something simular for DirectSound and DirectInput?

If I can help with something, I'm more or less free. Maybe I'll learn something in the process.

**Comment by gonutz** [comment]
Yes I do have two projects: [mixer](https://github.com/gonutz/mixer) and [di8](https://github.com/gonutz/di8) but they are not ready for prime time, yet. I use them for my private projects and they suffice for that. But these libraries still have limitations.
The mixer lib uses a sub-package called dsound but that only calls the minimum DirectSound8 API needed to get the sound out, it is not a complete wrapper like d3d9. Also the wav package only reads 44100 Hz wave files. This needs some more work before I will promote it to a greater audience.
The di8 package is for DirectInput8 and is supposed to become a full wrapper for the whole API. It is already usable but has no documentation yet.

**Comment by mzbab88** [comment]
Incomplete is probably even better, I doubt I would be able to understand a complete one.

I don't really need documentation, but a few examples of usage would be priceless.

**Comment by gonutz** [comment]
Hey, I just uploaded a project I created a couple of weeks ago. It is [a little program](https://github.com/gonutz/pad2game) I wrote to translate the input of a game pad I have to mouse and keyboard events on Windows so that I can play No more Room in Hell with it. It was a nice use for the DirectInput8 wrapper. You can check out the code, it is half DI8 and half Windows specific code for emulating keyboard and mouse input but you should find what you need to get going with DI8.
As for my [mixer library](https://github.com/gonutz/mixer), you can have a look at [loading a sound](https://github.com/gonutz/gophette/blob/master/main_windows.go#L429-L431) and [playing it](https://github.com/gonutz/gophette/blob/master/main_windows.go#L226) in my [gophette game](https://github.com/gonutz/gophette). The API is small and not finished yet. I am not yet sure about the way it should work on the user side so it is bound to change a lot once I get around to it.
Hope this helps, let me know if I can help you any further.

**Comment by mzbab88** [comment]
I see that you made the [windows.OpenWindow function](https://github.com/gonutz/gophette/blob/master/main_windows.go#L134). What do you think, maybe it should return something like Window type instead of int? Something that I can later Close, Resize, Move, Minimize, Maximize, etc. Just a suggestion.

If you'll make a type Window with methods Close and Maximize, I'll so going to steal your code.

**Comment by gonutz** [comment]
Please feel free to go ahead and rob me of my code ;)
This was written for a hackathon and I have not been working on that code for a while so it will for now stay the way it is but you could of course use it as a base for a more sophisticated Windows API wrapper. This was only the bare minimum to get the game running.
Usually I use other platform layer wrappers, check out [Allen Dang's w32 library](https://github.com/AllenDang/w32) for a nice Windows API wrapper and [SDL2 for Go](https://github.com/veandco/go-sdl2) which is cross-platform and gives you a nice uniform platform layer for every OS.

**Comment by mzbab88** [comment]
Well, don't know.

w32 library is unusable by itself without some wrapper, your go programs will end up looking like an even more weird C.

And SDL2, I suspect that it's too fat for me to understand anything inside. I doubt I will find the code even for creating window inside of it. Also, it's in C, it probably should be rewritten in Go, at least a subset of it.

**Comment by mzbab88** [comment]
I so miss interactive console from python, have you heard about something like that for go? I hope somebody is working on that. It really is it's killer feature.
