### ISSUE TITLE
Surface.LockRect -> Invalid call

### ISSUE THREAD

**Issue by namkazt** [gonutz/d3d9#2]
I got error when use lockrect from backbuffer surface: 

```
var rc d3d9.RECT
surface, err := device.GetBackBuffer(0, 0, d3d9.BACKBUFFER_TYPE_MONO)
defer surface.Release()
lockedRect, err := surface.LockRect(&rc, 0)
... err here.
```

**Comment by gonutz** [comment]
I think this may be because the back buffer is not lockable in your case. If you look at [this MSDN link](https://msdn.microsoft.com/en-us/library/windows/desktop/bb205896(v=vs.85).aspx) it gives you certain situations in which you cannot lock the back buffer, down in the remarks it says:

> A multisample back buffer cannot be locked.

and also

> This method cannot retrieve data from a surface that is is contained by a texture resource created with D3DUSAGE_RENDERTARGET because such a texture must be assigned to D3DPOOL_DEFAULT memory and is therefore not lockable. In this case, use instead IDirect3DDevice9::GetRenderTargetData to copy texture data from device memory to system memory.

This is only a guess, maybe you can post a complete running example with a minimal amount of code, so that I can copy it to a file that can easily be `go run` to look for other issues in the code.

**Comment by namkazt** [comment]
i see. thank you. 
anyway im stucking on copySurfacefromSurface function to copy backBuffer to pool.
That functions is from D3Dx9.
any ideas how to do it ?

**Comment by gonutz** [comment]
I am not really sure what you are trying to accomplish.

This is a wrapper explicitely for D3D9 and D3Dx9 is not included. It would of course be possible to create a Go wrapper for that as well, structured in the same way as this one.

Googling the function CopySurfaceFromSurface I only find [this link](http://mathinfo.univ-reims.fr/image/dxBase/codes/06/02_BackBuffer.cpp.html) which also calls LockRect in its implementation so as I stated above, one of the surfaces might not be lockable.

The issue that you have is with using the D3D API and not an issue with this Go wrapper library. I might still be able to help you if you post a code example, though. Otherwise you could refer to the MSDN forums or other game related forums for help.

**Comment by gonutz** [comment]
Since this is not an issue with the library but rather an issue with the D3D9 API, I will close this issue.
You can however still comment here and I am happy to help if I can.
